### PR TITLE
Few issues/enhancement

### LINKED ISSUE #7: [Feature] Loading Indicator for Practice Mode
While loading questions (a half a second, so minor improvement) we can see `Loading...` in the Practice Mode, which isn't much visible and not centered. Would be good to have some nicely centered Loading Indicator for that.

Screenshot 2024-03-26 at 11 02 30

### LINKED ISSUE #14: [BUG] Improve Pagination
**Describe the bug**
Pagination arrows aren't visible until you manually enter previous questions.

**To Reproduce**
1. Go to `any exam`
2. Click on `Practice Mode`
3. Click `Next question`
4. Move to the previous question by entering the number of a previous question by clicking into the input field where number of question is.
5. A `Next` arrow will popup. `Back` arrow is missing.

**Expected behavior**
1. `Next` arrow is visible all the time.
2. `Back` arrow is not missing.

**Screenshots**

Screenshot 2024-04-11 at 18 05 34
Screenshot 2024-04-11 at 18 06 00

**Desktop (please complete the following information):**
 - OS: `any`
 - Browser: `any`
 - Version: `any`

**Smartphone (please complete the following information):**
 - Device: `any`
 - OS: `any`
 - Browser: `any`
 - Version: `[e.g. 22]`

**Additional context**
n/a.

### PR DESCRIPTION
**Pull request by cbvora**
Fixes #14 
Fixes #7 

- [x] I have read and agree to the [Code of Conduct](CODE_OF_CONDUCT.md), and have followed the [Contributing guidelines](CONTRIBUTING.md).

## Pull Request Type

- [x] Bug fix (please link related issues if applicable)
- [x] New feature

## Summary
- Making the Next and Previous arrow icons visible all the time. if the next question is not available, next icon will be disabled. same for prev icon
- Clicking on Next or Previous will maintain the selection on the particular question
- Unique URL to each question, so that user can share the particular question and revisit it later
- close Image modal on click of ESC and outside of image
- Seach exam in home page
- Got to specific que in practise mode using input.
- custom debounce hook 
- proper loader through the app

### CODE REVIEW

**Comment by danieldanielecki** [comment]
First of all, looking absolutely fantastic.

1. Love the search feature.
2. Love the navigation.
3. Love the param in the URL.
4. Are you planning to add a feature from my compliments at 2. & 3. to `Exam Mode`?
5. When a Student enters just 1 number in the input field for `Q&A` the page refreshes immediately, but what about if the Student wants to input a question between `10` and `99`, or even with 3 numbers? It's a little bit inconvenient. Can we have a [debounce](https://stackoverflow.com/questions/23123138/how-can-i-perform-a-debounce) for that?
6. What about when the Student reaches the last question? See the screenshot below.
Screenshot 2024-06-14 at 16 55 12

**Comment by danieldanielecki** [comment]
Created a couple of issues for points 4., 5. & 6.

@cbvora thank you so much for contributing, and if you'd like to create some notes while learning DSA's, feel free ;-) our community would've been definitely glad for it, and you might get some help/feedback/more visibility!

I'm creating one such a resource now, for `HTML`: https://github.com/Ditectrev/Awesome-HTML-Book-HyperText-Markup-Language-HTML.

File: components/QuizForm.tsx [hunk 1]
```diff
@@ -107,30 +140,65 @@ const QuizForm: FC<Props> = ({
...
             onClick={() => {
-              if (currentQuestionIndex < lastIndex + 2) {
-                setShowCorrectAnswer(true);
-              } else {
-                setShowCorrectAnswer(false);
-              }
-              reset();
               handleNextQuestion(currentQuestionIndex - 1);
             }}
-            disabled={!(currentQuestionIndex > 1) || !canGoBack}
```
Comment (danieldanielecki) [inline components/QuizForm.tsx:133]: it was actually better, reverting in the coming commit

File: components/QuizForm.tsx [hunk 2]
```diff
@@ -152,38 +220,19 @@ const QuizForm: FC<Props> = ({
...
-            onClick={() => {
-              if (currentQuestionIndex < lastIndex) {
-                setShowCorrectAnswer(true);
-              } else {
-                setShowCorrectAnswer(false);
-              }
-              reset();
-              handleNextQuestion(currentQuestionIndex + 1);
-            }}
-            disabled={!(currentQuestionIndex < lastIndex)}
```
Comment (danieldanielecki) [inline components/QuizForm.tsx:186]: it was actually better, reverting in the coming commit
